### ISSUE TITLE
Check if username is unique

### ISSUE THREAD

**Issue by QueenBeta** [CMPUT301W22T00/QRHunt#215]

**Comment by Mattwmaster58** [comment]
rejection sampling is probably an ok way to do this. This will need to be implemented at 2 points: account creation and edit profile stage

**Comment by kezzayuno** [comment]
Good point. @Mattwmaster58 Any tips on how I should go about this? I'm just thinking a simple while look that checks all usernames present in the db

**Comment by Mattwmaster58** [comment]
Sure. You would basically just `QuerySnapshot.empty` property to determine whether or not someone already has this username. I think you can safely ignore creation username unique constraints - 1000 adjectives * 1000 nouns * 1000 numbers = 1 in a billion chance it's not unique. I'll take those odds. 

For editing the profile,  you could do it simply checking when they click OK. This has its drawbacks tho - if for example, they added/edited email/social profiles, but the username wasn't unique - it might be annoying to save only those fields (definitely can be done).

The _ideal_ way in my mind for ease of use in my mind is sorta the way insta does it if you're familiar. As soon as a user changes the username input field at all, we disable the save button and show a loading icon. Spamming the DB on every request is non-ideal, especially because by the time we get most of the responses they'll be useless anyway. So for example, if they added "1234123" to their username of "bob", you're sending requests for "bob1", "bob12", "bob123" ... "bob1234123".

So to combat this, we could  start maybe a 500ms countdown before a database request is sent off (how you'd do this in JS would be setTimeout, how in Java I do not know), and every time another input change is received, we reset this countdown. When this countdown runs out make a new one to the database:

```java
        db.collection("users")
                .whereEqualTo("username", "<actual username here>")
                .whereNotEqualTo(FieldPath.documentId(), player.getPlayerId())
                .get()
                .addOnCompleteListener(
                        qSnapshot -> {
                            if (qSnapshot.isSuccessful()) {
                                if (qSnapshot.getResult().isEmpty()) {
                                    // enable the save button, show checkmark icon etc
                                } else {
                                    // show x, callout "username is taken",
                                    // keep save button disabled
                                }
                            }
                        });
```

A pitfall in this approach is the race condition that might occur if we get results out of order. For example, let's say we query for bob1 and then later on bob2. bob2 returns first for some reason, and then bob1 returns. bob1 is unique, so the user is allowed to save bob2 as their username, even though it may not be unique - I'm not sure the best way to address this. Ideally you  cancel any existing queries, but this isn't trivial to do, here's what I came up with though:

<details>
  <summary>Click to expand!</summary>
```java
public class UniqueUsernameVerifier {
    private final String username;
    private final View checkmark;
    private final Button saveButton;
    private final String playerId;
    private boolean cancelled;

    public UniqueUsernameVerifier(
            String username, String playerId, View checkmark, Button saveButton) {
        this.username = username;
        this.playerId = playerId;
        this.checkmark = checkmark;
        this.saveButton = saveButton;
    }

    public void cancel() {
        cancelled = true;
    }

    public boolean isCancelled() {
        return cancelled;
    }

    public void checkUsername() {
        FirebaseFirestore.getInstance()
                .collection("users")
                .whereEqualTo("username", "<actual username here>")
                .whereNotEqualTo(FieldPath.documentId(), username)
                .get()
                .addOnCompleteListener(
                        qSnapshot -> {
                            if (qSnapshot.isSuccessful() && !isCancelled()) {
                                if (qSnapshot.getResult().isEmpty()) {
                                    // enable the save button, show checkmark icon etc
                                } else {
                                    // show x, callout "username is taken",
                                    // keep save button disabled
                                }
                            }
                        });
    }
}
```
</details>


And the usage:
```java

// after our 500ms countdown has expired
if (verifier !== null) {
    verifier.cancel()
}
verifier = new UniqueUsernameVerifier(...)
```
